GoFly_web/Controllers/BusController.cs
using GoFly_web.Managers.GoFlys;
using Microsoft.AspNetCore.Mvc;

namespace GoFly_web.Controllers
{
    public class BusController : Controller
    {
        private readonly IBusManager _manager;

        public BusController(IBusManager manager)
        {
            _manager = manager;
        }
        public IActionResult Bus()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchBus(string DepartureCity, string ArrivalCity, string DepartureDate, string ArrivalDate, int Persons)
        {
            var _busTickets = await _manager.Search(DepartureCity, ArrivalCity, DepartureDate, ArrivalDate);
            ViewBag.BusTickets = _busTickets;
            ViewBag.BusPersons = Persons;
            return View();
        }

    }
}

GoFly_web/Controllers/HistoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace GoFly_web.Controllers
{
    public class HistoryController : Controller
    {
        public IActionResult History()
        {
            return View();
        }
    }
}

GoFly_web/Controllers/HotelController.cs
using GoFly_web.Managers.GoFlys;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;

namespace GoFly_web.Controllers
{
    public class HotelController : Controller
    {
        private readonly IHotelManager _manager;

        public HotelController(IHotelManager manager)
        {
            _manager = manager;
        }

        public async Task<IActionResult> Index()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.hotels = await _manager.GetAll();
            var hotels = await _manager.GetAll();
            return View(mymodel);
        }


        [HttpPost]
        public IActionResult CreateHotel(double price, int stars, int placeNumber, string name, string city)
        {
            _manager.CreateHotel(price, stars, placeNumber, name, city);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DeleteHotel(int hotelId)
        {
            _manager.DeleteHotel(hotelId);
            return RedirectToAction(nameof(Index));
        }

        public RedirectResult GoToAdminHome()
        {
            return Redirect("/AdminHome/Index");
        }
    }
}

GoFly_web/Controllers/HotelsController.cs
using GoFly_web.Managers;
using GoFly_web.Managers.GoFlys;
using GoFly_web.Storage.Entity;
using Microsoft.AspNetCore.Mvc;

namespace GoFly_web.Controllers
{
    public class HotelsController : Controller
    {
        private readonly IHotelsManager _manager;

        public HotelsController(IHotelsManager manager)
        {
            _manager = manager;
        }
        public IActionResult Hotels()
        {
            return View();
        }

       

        [HttpPost]
        public async Task<IActionResult> SearchHotels(string Icity, int Persons,
            int ThreeStars, int FourStars, int FiveStars, string CheckInDate, string CheckOutDate)
        {
            var _hotels = await _manager.Search(Icity,ThreeStars, FourStars, FiveStars);
            ViewBag.Hotel = _hotels;
            ViewBag.Persons = Persons;
            var checkInDate = DateTime.Parse(CheckInDate);
            var checkOutDate = DateTime.Parse(CheckOutDate);
            ViewBag.Days = ((checkOutDate - checkInDate).Days);
            if(ViewBag.Days < 1) { ViewBag.Days = 1; }
            ViewBag.starThree = ThreeStars;
            ViewBag.starFour = FourStars;
            ViewBag.starFive = FiveStars;
            return View();
        }


    }
}

GoFly_web/Controllers/PlaneController.cs
using GoFly_web.Managers;
using GoFly_web.Managers.GoFlys;
using GoFly_web.Storage.Entity;
using Microsoft.AspNetCore.Mvc;


namespace GoFly_web.Controllers
{
    public class PlaneController : Controller
    {

        private readonly IPlaneManager _manager;

        private readonly IAccountManager _accountmanager;
        public PlaneController(IPlaneManager manager, IAccountManager accountManager)
        {
            _manager = manager;
            _accountmanager = accountManager;   
        }
        public IActionResult Plane()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchPlane(string DepartureCity, string ArrivalCity, string DepartureDate, string ArrivalDate, int Persons)
        {
            var _planeTickets = await _manager.Search(DepartureCity, ArrivalCity, DepartureDate, ArrivalDate);
            ViewBag.PlaneTickets = _planeTickets;
            ViewBag.PlanePersons = Persons;
            return View();
        }

        [HttpPost]
        public IActionResult Plane(string Email, string Password)
        {
            var user = _accountmanager.Login(Email, Password);
            if (user != null)
            {
                ViewBag.UserName = user.FirstName;
                TempData["UserName"] = user.FirstName;
            }

            return View();

        }

    }
}

GoFly_web/Controllers/RailwayController.cs
using GoFly_web.Managers.GoFlys;
using Microsoft.AspNetCore.Mvc;

namespace GoFly_web.Controllers
{
    public class RailwayController : Controller
    {
        private readonly ITrainManager _manager;

        public RailwayController(ITrainManager manager)
        {
            _manager = manager;
        }
        public IActionResult Railway()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchTrain(string DepartureCity, string ArrivalCity, string DepartureDate, string ArrivalDate, int Persons)
        {
            var _planeTickets = await _manager.Search(DepartureCity, ArrivalCity, DepartureDate, ArrivalDate);
            ViewBag.TrainTickets = _planeTickets;
            ViewBag.TrainPersons = Persons;
            return View();
        }
    }
}

GoFly_web/Views/Hotels/Hotels.cshtml
@{
    Layout=null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="~/css/Hotels.css"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoFly - поиск дешёвых билетов
    </title>
</head>
<body>
   <div class="container">
    <div class="toppanel">
        <a asp-area="" asp-controller="Plane" asp-action="Plane"><span id="Logo">GoFly</span></a>
        @*<a asp-area="" asp-controller="Favourite" asp-action="Favourite" id="Favorites">Избранное </a>*@
         <a asp-area="" asp-controller="History" asp-action="History" id="History">История путешествий</a>
          @if(TempData.Peek("UserName") == null)
          {
         <a asp-area="" asp-controller="Registration" asp-action="Registration" id="Registration">Зарегистрироваться</a>
          }
          else
          {
         <a asp-area="" asp-controller="Plane" asp-action="Plane" id="Registration">Добро пожаловать, @TempData.Peek("UserName")</a>
          }
            <a asp-area="" asp-controller="Feedback" asp-action="Feedback" id="Feedback">Отзывы</a>
    </div>

        <div class="buttons">

            <div class="planes">
                <a asp-area="" asp-controller="Plane" asp-action="Plane">
                <div class="imgBorder">
                    <img src="../Images/planes.png" alt="">
                </div>
                <p>Авиабилеты</p>
                </a>
            </div>
            
            <div class="trains">    
                <a asp-area="" asp-controller="Railway" asp-action="Railway">        
                <div class="imgBorder">
                <img src="../Images/train.png" alt="">
                </div>
                <p>Ж/Д билеты</p>
                </a>
            </div>


            <div class="buses">
                <a asp-area="" asp-controller="Bus" asp-action="Bus"> 
                <div class="imgBorder">
                    <img src="../Images/bus.png" alt="">
                </div>
                    <p>Автобусы</p>
                </a>
            </div>

            <div class="hotels">
                <div class="imgBorder">
                    <img src="../Images/hotel.png" alt="">
                </div>
                    <p>Отели</p>
            </div>

            <div class="topCities">
                <a asp-area="" asp-controller="TopCities" asp-action="TopCities">
                <div class="imgBorder">
                    <img src="../Images/topCities.png" alt="">
                </div>
                    <p>Все города</p>
                </a>
            </div>

        </div>
    <div>
      @using(Html.BeginForm("SearchHotels", "Hotels", FormMethod.Post)) 
      {
    <div class="searchPannel">
        <input required type="search" name="Icity" id="Departure" placeholder="Введите город или название отеля" list="">
        <!-- <input type="search" name="Arrival" id="Arrival" placeholder="Куда"> -->
        <input type="date" name="CheckInDate" id="DataDeparture" min="2022-06-02" >
        <p id=OneWayTitle>Заезд</p>
        <input type="date" name="CheckOutDate" id="DataArrival" min="2022-06-02" >
        <p id=RoundTripTitle>Выезд</p>
        <div class="PeopleAmount">        
            <button class="bt_minus" type="button">-</button>
            <input type="text" class="quantity" name="Persons" value="1" data-max-count="8">
            <button class="bt_plus" type="button">+</button>
        </div>
        <p id=AmountTitle>Количество <br> людей</p>
       <div class="CheckBoxes">
        <input type="checkbox" name="FiveStars" id="CheckBox5Star" value="5" >
        <label id="CheckBoxLabel5" for="CheckBox5Star">5★</label>
        <input type="checkbox" name="FourStars" id="CheckBox4Star" value="4" >
        <label id="CheckBoxLabel4" for="CheckBox4Star">4★</label>
        <input type="checkbox" name="ThreeStars" id="CheckBox3Star" value="3" >
        <label id="CheckBoxLabel3" for="CheckBox3Star">3★</label>
        <p id=HotelStarTitle>Искать отели с</p>
        </div>
 
        <div class="searchButton">
            <button class="btn-1" type="submit">Найти отели</button>
        </div>
@*        <div id="success" class="button"><a asp-area="" asp-controller="FavouriteHotel" asp-action="FavouriteHotel"><img id="wishlistImg" src="../Images/heart_full.png" alt=""></a></div>
        <div class="notify"><span id="notifyType" class=""></span></div>*@
    </div>
    }
    </div>
    
        <div class="bottompanel">
            <p>Безопасные платежи с </p>
            <span>PENKOFF</span>

        </div>
       
        @if (TempData.Peek("UserName") == null)
        {
             @using(Html.BeginForm("Login", "Registration", FormMethod.Post)) 
             {
                <div class="autorizationPannel">
                    <a href="#" class="LoginMenu_btn" id="Login">Войти</a>
                    <nav class="autorizationPannelParameters">
                        <p id="autorizationTitle">Авторизация</p>
                        <input requierd id="InputLogin" name="Email" type="text" placeholder="Введите логин сюда">
                        <input required id="InputPassword" name="Password" type="password" placeholder="Введите пароль сюда">
                        <button id = "EnterButton">Вход</button>
                        <div class="autorizationInfo">
                            <p>Забыли пароль?</p>
                            <a href="#">Нажмите</a>
                            <p>для восстановления <br> Нет аккаунта?</p>
                            <a asp-area="" asp-controller="Registration" asp-action="Registration">Зарегистрируйтесь</a>
                        </div>
                    </nav>
                </div>
            }
        }
         @if (TempData.Peek("UserName") != null)
        {
           <a class="Quit" asp-area="" asp-controller="Registration" asp-action="Logout" id="Quit">Выйти</a>
        }
    </div>
</div>
<</body>>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>// Убавляем кол-во по клику
        $('.PeopleAmount .bt_minus').click(function() {
        let $input = $(this).parent().find('.quantity');
        let count = parseInt($input.val()) - 1;
        count = count < 1 ? 1 : count;
        $input.val(count);
    });
    // Прибавляем кол-во по клику
    $('.PeopleAmount .bt_plus').click(function() {
        let $input = $(this).parent().find('.quantity');
        let count = parseInt($input.val()) + 1;
        count = count > parseInt($input.data('max-count')) ? parseInt($input.data('max-count')) : count;
        $input.val(parseInt(count));
    }); 
    // Убираем все лишнее и невозможное при изменении поля
    $('.PeopleAmount .quantity').bind("change keyup input click", function() {
        if (this.value.match(/[^0-9]/g)) {
            this.value = this.value.replace(/[^0-9]/g, '');
        }
        if (this.value == "") {
            this.value = 1;
        }
        if (this.value > parseInt($(this).data('max-count'))) {
            this.value = parseInt($(this).data('max-count'));
        }    
    }); 

    $('.LoginMenu_btn').on('click',function(e){
        e.preventDefault();
        $('.autorizationPannel').toggleClass('autorizationPannel_Active')
    })

    $("#success").click(function () {
      $(".notify").toggleClass("active");
      $("#notifyType").toggleClass("success");
  
      setTimeout(function(){
        $(".notify").removeClass("active");
        $("#notifyType").removeClass("success");
      },2000);
    });

    </script>
            <script>
	$(document).ready( function() {
    var now = new Date();
    var month = (now.getMonth() + 1);               
    var day = now.getDate();
	var day1 = day + 5;
    if (month < 10) 
        month = "0" + month;
    if (day < 10) 
        day = "0" + day;
        if (day1 < 10)
            day1 = "0" + day1;

    var today = now.getFullYear() + '-' + month + '-' + day;
        
        var tommorow = now.getFullYear() + '-' + month + '-' + day1;

    $('#DataDeparture').val(today);
	$('#DataArrival').val(tommorow);
}); 
    </script>
</html>

GoFly_web/Views/Hotels/SearchHotels.cshtml
@page
@*ViewBag.Hotel
  ViewBag.Persons
  ViewBag.Days
  ViewBag.starThree
  ViewBag.starFour
  ViewBag.starFive
*@
@{
    Layout=null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/css/SearchResultHotel.css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Результаты поиска</title>
</head>
<body>
    <div class="container">
    <div class="toppanel">
        <a asp-area="" asp-controller="Plane" asp-action="Plane"><span id="Logo">GoFly</span></a>
        <a asp-area="" asp-controller="Favourite" asp-action="Favourite" id="Favorites">Избранное </a>
         <a asp-area="" asp-controller="History" asp-action="History" id="History">История путешествий</a>
        <a asp-area="" asp-controller="Registration" asp-action="Registration" id="Registration">Зарегистрироваться</a>
        <a asp-area="" asp-controller="Feedback" asp-action="Feedback" id="Feedback">Отзывы</a>
    </div>
        <div class="autorizationPannel">
            <a href="#" class="LoginMenu_btn" id="Login">Войти</a>
            <nav class="autorizationPannelParameters">
                <p id="autorizationTitle">Авторизация</p>
                <input id="InputLogin" type="text" placeholder="Введите логин сюда">
                <input id="InputPassword" type="password" placeholder="Введите пароль сюда">
                <button id = "EnterButton">Вход</button>
                <div class="autorizationInfo">
                    <p>Забыли пароль?</p>
                    <a id="AutorizationPress" href="#">Нажмите</a>
                    <p>для восстановления <br> Нет аккаунта?</p>
                    <a id="AutorizationRecover"href="#">Зарегистрируйтесь</a>
                </div>
            </nav>
        </div>
    @if(ViewBag.Hotel.Count == 0)
        {
           <p id="Title">Ничего не найдено</p> 
        } else
        {
        <p id="Title">Результаты поиска</p>
        }

        <div class="table">
            <table>
                <tr>
                    <th>Город</th>
                    <th>Название</th>
                    <th>Колличество мест</th>
                    <th>Цена</th>
                    <th>Звёзды</th>
                    <th></th>
                @foreach(var _hotel in ViewBag.Hotel)
                {
                <tr>
                    <td>@_hotel.ArrivalCityName</td>
                    <td>@_hotel.Name</td>
                    <td>@_hotel.PlacesNumber</td>
                    <td>@(_hotel.Price * ViewBag.Persons * ViewBag.Days)</td>
                    <td>@_hotel.StarRating</td>
                    <td><button>Купить</button></td>
                </tr>
                }

            </table>
       
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
$('.LoginMenu_btn').on('click',function(e){
    e.preventDefault();
    $('.autorizationPannel').toggleClass('autorizationPannel_Active')
})
</script>

</html>