GoFly_web/Controllers/FavouriteController.cs
using Microsoft.AspNetCore.Mvc;

namespace GoFly_web.Controllers
{
    public class FavouriteController : Controller
    {
        public IActionResult Favourite()
        {
            return View();
        }
    }
}

GoFly_web/Controllers/FeedbackController.cs
using GoFly_web.Managers.GoFlys;
using Microsoft.AspNetCore.Mvc;

namespace GoFly_web.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IFeedbackManager _manager;




        public FeedbackController(IFeedbackManager manager)
        {
            _manager = manager;
        }
      

        public async Task<IActionResult> Feedback()
        {
            var feedbacks = await _manager.GetAll();
            return View(feedbacks);
        }

        [HttpPost]
        public IActionResult CreateFeedback(string description)
        {
            
              
             _manager.CreateFeedback("taiwan.profiler@mail.ru", description);
            return RedirectToAction(nameof(Feedback));
        }
    }
}

GoFly_web/Controllers/HistoryBusController.cs
using Microsoft.AspNetCore.Mvc;

namespace GoFly_web.Controllers
{
    public class HistoryBusController : Controller
    {
        public IActionResult HistoryBus()
        {
            return View();
        }
    }
}

GoFly_web/Controllers/HistoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace GoFly_web.Controllers
{
    public class HistoryController : Controller
    {
        public IActionResult History()
        {
            return View();
        }
    }
}

GoFly_web/Controllers/PlaneController.cs
using GoFly_web.Managers;
using GoFly_web.Managers.GoFlys;
using GoFly_web.Storage.Entity;
using Microsoft.AspNetCore.Mvc;


namespace GoFly_web.Controllers
{
    public class PlaneController : Controller
    {

        private readonly IPlaneManager _manager;

        private readonly IAccountManager _accountmanager;
        public PlaneController(IPlaneManager manager, IAccountManager accountManager)
        {
            _manager = manager;
            _accountmanager = accountManager;   
        }
        public IActionResult Plane()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchPlane(string DepartureCity, string ArrivalCity, string DepartureDate, string ArrivalDate, int Persons)
        {
            var _planeTickets = await _manager.Search(DepartureCity, ArrivalCity, DepartureDate, ArrivalDate);
            ViewBag.PlaneTickets = _planeTickets;
            ViewBag.PlanePersons = Persons;
            return View();
        }

        [HttpPost]
        public IActionResult Plane(string Email, string Password)
        {
            var user = _accountmanager.Login(Email, Password);
            if (user != null)
            {
                ViewBag.UserName = user.FirstName;
                TempData["UserName"] = user.FirstName;
            }

            return View();

        }

    }
}

GoFly_web/Views/History/History.cshtml
@{
    Layout=null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="~/css/History.css">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoFly - поиск дешёвых билетов
    </title>
</head>
<body>
    <div class="container">
    <div class="toppanel">
        <a asp-area="" asp-controller="Plane" asp-action="Plane"><span id="Logo">GoFly</span></a>
        @*<a asp-area="" asp-controller="Favourite" asp-action="Favourite" id="Favorites">Избранное </a>*@
         <a asp-area="" asp-controller="History" asp-action="History" id="History">История путешествий</a>
          @if(TempData.Peek("UserName") == null)
          {
         <a asp-area="" asp-controller="Registration" asp-action="Registration" id="Registration">Зарегистрироваться</a>
          }
          else
          {
         <a asp-area="" asp-controller="Plane" asp-action="Plane" id="Registration">Добро пожаловать, @TempData.Peek("UserName")</a>
          }
            <a asp-area="" asp-controller="Feedback" asp-action="Feedback" id="Feedback">Отзывы</a>
    </div>





        </div>
        @if (TempData.Peek("UserName") == null)
        {
             @using(Html.BeginForm("Login", "Registration", FormMethod.Post)) 
             {
                <div class="autorizationPannel">
                    <a href="#" class="LoginMenu_btn" id="Login">Войти</a>
                    <nav class="autorizationPannelParameters">
                        <p id="autorizationTitle">Авторизация</p>
                        <input requierd id="InputLogin" name="Email" type="text" placeholder="Введите логин сюда">
                        <input required id="InputPassword" name="Password" type="password" placeholder="Введите пароль сюда">
                        <button id = "EnterButton">Вход</button>
                        <div class="autorizationInfo">
                            <p>Забыли пароль?</p>
                            <a href="#">Нажмите</a>
                            <p>для восстановления <br> Нет аккаунта?</p>
                            <a asp-area="" asp-controller="Registration" asp-action="Registration">Зарегистрируйтесь</a>
                        </div>
                    </nav>
                </div>
            }
        }
         @if (TempData.Peek("UserName") != null)
        {
           <a class="Quit" asp-area="" asp-controller="Registration" asp-action="Logout" id="Quit">Выйти</a>
        }
    </div>
        <p id="HistoryTitle">История путешествий</p>
                <div class="BoxPlane">
                    <span id="PlaneHistoryLink">На самолете</span>
                 </div>
             <a asp-area="" asp-controller="HistoryTrain" asp-action="HistoryTrain">
                <div class="BoxTrain">
                    <span id="TrainHistoryLink">На поезде</span>
                </div>
            </a>
            <a asp-area="" asp-controller="HistoryBus" asp-action="HistoryBus">
                <div class="BoxBus">
                    <span id="BusHistoryLink">На автобусе</span>
                </div>
            </a>
            <a asp-area="" asp-controller="HistoryHotel" asp-action="HistoryHotel">
            <div class="BoxHotel">
                <span id="HotelHistoryLink">История брони отелей</span>
            </div>
            </a>
        </div>
        <div class="table">
            <table>
                 <tr>
                    <th>Откуда</th>
                    <th>Куда</th>
                    <th>Дата вылета</th>
                </tr>
                
                <tr>
                    <td>Москва, Россия</td>
                    <td>Ярославль, Россия</td>
                    <td>28.05.2022</td>
                </tr>

                <tr>
                    <td>Москва, Россия</td>
                    <td>Минск, БелоруССИЯ</td>
                    <td>28.05.2022</td>
                </tr>

                <tr>
                    <td>Минск, БелоруССИЯ</td>
                    <td>Москва, Россия</td>
                    <td>28.05.2022</td>
                </tr>

                <tr>
                    <td>Ярославль, Россия</td>
                    <td>Москва, Россия</td>
                    <td>28.05.2022</td>
                </tr>
                
            </table>
        </div>
    <div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
$('.LoginMenu_btn').on('click',function(e){
    e.preventDefault();
    $('.autorizationPannel').toggleClass('autorizationPannel_Active')
})
</script>

</html>