GoFly_web/Controllers/ArrivalCountryController.cs
using GoFly_web.Managers.GoFlys;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace GoFly_web.Controllers
{
    public class ArrivalCountryController : Controller
    {

        private readonly IArrivalCountryManager _manager;




        public ArrivalCountryController(IArrivalCountryManager manager)
        {
            _manager = manager;
        }

        public async Task<IActionResult> Page()
        {
            var countries = await _manager.GetAll();
            return View(countries);
        }

        public RedirectResult GoToDepCountry()
        {
            return Redirect("/DepartureCountry/Page");
        }

        public RedirectResult GoToAdminHome()
        {
            return Redirect("/AdminHome/Index");
        }


        [HttpPost]
        public IActionResult DeleteCountry(int countryId)
        {
            _manager.DeleteCountry(countryId);
            return RedirectToAction(nameof(Page));
        }

        [HttpPost]
        public IActionResult CreateCountry(string name)
        {
            _manager.CreateCountry(name);
            return RedirectToAction(nameof(Page));
        }

     
    }
}

GoFly_web/Views/ArrivalCountry/Page.cshtml
@{
    Layout=null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/css/ArrivalCountry.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Панель администратора</title>
</head>

@model ICollection<GoFly_web.Storage.Entity.ArrivalCountry>

    <div class="menu">
        <p>Страны Прибытия</p>      
    </div>


<div class="existing">
<table> 
    <tr>
        <th>Identification number</th>
        <th>Name</th>
    </tr>
    @foreach(var country in Model)
    {
        <tr>
            <td>@country.Id</td>
            <td>@country.Name</td>
        </tr>
    }
</table>
</div>

<div class="deleting">
<div>
    <p>Удаление объекта</p>
    @using(Html.BeginForm("DeleteCountry", "ArrivalCountry", FormMethod.Post))
    {
		<input type="text" name ="countryId" placeholder="Identification number Name CountryId">
        <button type = "submit">Удалить</button>
        @*<textarea name ="countryId" id = "countryId"></textarea>
        <button type = "submit">Deduct</button>*@
    }
</div>
</div>


<div class = "adding">
		<p>Добавление объекта</p>

    @using(Html.BeginForm("CreateCountry", "ArrivalCountry", FormMethod.Post))
    {
     
        @*<textarea name = "name"></textarea>*@
        <input type="text" placeholder="string name" name = "name">
        <button type = "submit">Добавить</button>
    }
</div>


<a asp-area="" asp-controller = "AdminHome" asp-action = "Index">
    <div class="returnButton">
        <p>Вернуться на главную</p>
    </div>
    </a>

@*<div>
    <h1>Message</h1>
    @using(Html.BeginForm("SendEmailDefault", "ArrivalCountry"))
    {
     
        <button type = "submit">Message</button>
    }
</div>*@

@*@Html.ActionLink("Перейти","GoToDepCountry")
 <h1>переход</h1>

@Html.ActionLink("К домашней админа","GoToAdminHome")*@